In [1]:
%load_ext autoreload
%autoreload 2

import numpy as np
from scipy.optimize import minimize
from scipy.optimize import fsolve
from matplotlib import pyplot as plt
import pandas as pd

import sys
sys.path.append("../")
from bargains_logit import *

In [2]:
COST =5
WTP =  np.array([25,25])
MC = np.array([0,0])

print(simult_bargain(15,15,COST,WTP,MC,active=True))
print(seq_bargain(15, COST, WTP, MC))

(array([15.72607688]), array([15.72216797]))
(array([15.8158953]), array([17.14908905]))


In [3]:
WTP = np.array([25,25])
print(seq_bargain(15, COST, WTP, MC))

(array([15.8158953]), array([17.14908905]))


In [ ]:
import warnings
warnings.filterwarnings('ignore')

def solve_parameters_obj(phi_obs, p_obs, cost, wtp, betas, active=True):
    mc_i  = np.array([0,0])
    phi1,phi2 = simult_bargain(15,15,cost,wtp,mc_i,betas=betas,active=active)


    p1, p2, s1,s2, profits1,profits2 = calc_profits_price_shares(phi1,phi2,cost, wtp, mc_i)

    phi = np.array([phi1[0],phi2[0]])
    p = np.array([p1[0],p2[0]])
    return ((phi-phi_obs)**2).sum() + ((p-p_obs)**2).sum()

def solve_parameters(phi_obs,p_obs,wtp=25,cost=5,active=True): 
    obj = lambda betas : solve_parameters_obj(phi_obs, p_obs, cost, wtp, betas, active=active)
    beta_implied = minimize(obj, [.5,.5], options={'fatol':1e-2,'xatol':1e-2,'maxiter':20},method='Nelder-Mead').x # 
    return beta_implied


for i in range(0,3):
    #seq_phi1,seq_phi2 = seq_bargain(15, COST+i, WTP, MC)
    #print(seq_phi1,seq_phi2)
    seq_phi1,seq_phi2 = np.array([15.96286645]), np.array([17.33714647])
    seq_phi =  np.array([seq_phi1[0],seq_phi2[0]])
    seq_p1, seq_p2, _,_,_,_= calc_profits_price_shares(seq_phi1[0],seq_phi2[0], COST+i, WTP, MC)
    seq_p = np.array([seq_p1, seq_p2])
    beta = solve_parameters( seq_phi,seq_p , wtp=WTP,cost= COST+i )
    result = (COST+i, WTP[0], seq_phi1[0], seq_phi2[0], seq_p1, seq_p2, beta[0],beta[1])
    print('%.3f,%.3f,%.3f,%.3f,%.3f,%.3f,%.3f,%.3f'%result)


5.000,25.000,15.963,17.337,23.955,24.710,0.423,0.203
6.000,25.000,15.963,17.337,25.127,25.932,0.500,0.500


# 