In [2]:
%load_ext autoreload
%autoreload 2

import numpy as np
from scipy.optimize import minimize
from scipy.optimize import fsolve
from matplotlib import pyplot as plt
import pandas as pd

import sys
sys.path.append("../")
from bargains_logit import *

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [4]:
COST =5
WTP =  np.array([25,25])
MC = np.array([0,0])

print(simult_bargain(15,15,COST,WTP,MC,active=True))
print(seq_bargain(15, COST, WTP, MC))

(array([13.92938232]), array([13.93029785]))
(array([15.]), array([12.28417969]))


In [5]:
WTP = np.array([25,26])
print(seq_bargain(30, COST, WTP, MC))

(array([15.33690262]), array([12.68554688]))


In [6]:
def solve_parameters_obj(phi_obs, p_obs, cost, wtp,active=False):
    mc_i  = np.array([0,0])
    wtp2 = np.array([wtp,wtp])
    phi1,phi2 = simult_bargain(15,15,cost,wtp2,mc_i,active=active)
    p1,p2,s1,s2,profits1,profits2 = calc_profits_price_shares(phi1,phi2,cost,wtp2,mc_i)
    
    phi = np.array([phi1[0],phi2[0]])
    p = np.array([p1[0],p2[0]])
    return ((phi-phi_obs)**2).sum() + ((p-p_obs)**2).sum()


def solve_parameters(phi_obs,p_obs,wtp=np.array([25,25]),cost=5,active=True): 
    obj = lambda betas : solve_parameters_obj(phi_obs, p_obs, cost, wtp, betas, active=active)
    
    beta_implied = minimize(obj, [.5,.5], options={'fatol':1e-2,'xatol':1e-2,'maxiter':20},method='Nelder-Mead').x # 
    return beta_implied


for i in range(0,3):
    seq_phi1,seq_phi2 = seq_bargain(30, COST+i, WTP, MC)
    seq_phi =  np.array([seq_phi1[0],seq_phi2[0]])
    seq_p1, seq_p2 = calc_price(seq_phi1[0],seq_phi2[0], COST+i, WTP, MC)
    seq_p = np.array([seq_p1, seq_p2])
    beta = solve_parameters( seq_phi,seq_p , wtp=WTP,cost= COST+i )
    result = (COST+i, WTP, seq_phi1[0], seq_phi2[0], seq_p1, seq_p2, beta[0],beta[1])
    print('%.2f,%.2f,%.2f,%.2f,%.2f,%.2f,%.2f,%.2f'%result)


NameError: name 'calc_price' is not defined